repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.4.0
        hooks:
            -   id: check-yaml
                exclude: '^vendor/'
            -   id: end-of-file-fixer
                exclude: '^vendor/'
            -   id: trailing-whitespace
                exclude: '^vendor/'
    -   repo: local
        hooks:
            -   id: golangci-lint
                name: golangci-lint
                entry: make lint
                language: system
